# Generated by Django 5.1.7 on 2025-04-23 03:55

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finscope', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='user',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateField(verbose_name='Срок задания')),
                ('finscore', models.IntegerField(default=0, verbose_name='FinScores')),
                ('is_active', models.BooleanField(default=True)),
                ('add_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('task_participants', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Участники курса')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskDesk',
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
    ]
