# Generated by Django 5.1.7 on 2025-04-20 09:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0006_alter_openingbalance_cash_start_saldo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True)),
                ('add_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Планируемая сумма')),
                ('start_date', models.DateField(verbose_name='Дата окончания периода')),
                ('end_date', models.DateField(verbose_name='Дата окончания периода')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фактическая сумма')),
                ('points_progress', models.IntegerField(default=0, verbose_name='FinPoints')),
                ('add_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.taskdesk')),
            ],
        ),
    ]
