# Generated by Django 5.1.7 on 2025-04-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlimit',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения периода'),
        ),
        migrations.AlterField(
            model_name='budgetlimit',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма статьи'),
        ),
        migrations.AlterField(
            model_name='budgetlimit',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала периода'),
        ),
    ]
