# Generated by Django 5.1.7 on 2025-04-22 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budgetlimit_end_date_and_more'),
        ('transactions', '0006_alter_openingbalance_cash_start_saldo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='task',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='budgetlimit',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'subcategory'), name='unique_user_category_subcategory_limit'),
        ),
        migrations.DeleteModel(
            name='TaskDesk',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
