# Generated by Django 5.1.7 on 2025-04-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_testfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestFile',
        ),
    ]
