# Generated by Django 5.1.7 on 2025-04-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_user_cash_start_saldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Картинка профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cash_start_saldo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма денежных средств в наличии'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deposit_start_saldo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма денег на депозитных счетах'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='investment_start_saldo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма денег в инвестиционных активах'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='long_debt_start_saldo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма долгов с возвратом в течение более 12 мес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_debt_start_saldo',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма долгов с возвратом в течение 12 мес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
