# Generated by Django 5.1.7 on 2025-04-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar_alter_user_cash_start_saldo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cash_start_saldo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deposit_start_saldo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='investment_start_saldo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='long_debt_start_saldo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='short_debt_start_saldo',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, null=True, verbose_name='Уникальный псевдоним'),
        ),
    ]
