# Generated by Django 5.1.7 on 2025-04-14 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_start_saldo', models.IntegerField(blank=True, default=0, verbose_name='Сумма денежных средств в наличии')),
                ('deposit_start_saldo', models.IntegerField(blank=True, default=0, verbose_name='Сумма денег на депозитных счетах')),
                ('investment_start_saldo', models.IntegerField(blank=True, default=0, verbose_name='Сумма денег в инвестиционных активах')),
                ('short_debt_start_saldo', models.IntegerField(blank=True, default=0, verbose_name='Сумма долгов с возвратом в течение 12 мес')),
                ('long_debt_start_saldo', models.IntegerField(blank=True, default=0, verbose_name='Сумма долгов с возвратом в течение более 12 мес')),
                ('date_saldo_update', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=100, verbose_name='Тип операции')),
                ('category', models.CharField(choices=[('income', 'Доходы'), ('expense', 'Расходы'), ('deposit', 'Депозит'), ('investment', 'Инвестиции'), ('debt', 'Долг')], max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('income', 'Доходы'), ('expense', 'Расходы'), ('deposit', 'Депозит'), ('investment', 'Инвестиции'), ('debt', 'Долг')], max_length=100, verbose_name='Вид операции')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание транзакции')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
