# Generated by Django 5.1.7 on 2025-04-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_openningbalance_openingbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingbalance',
            name='cash_start_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Сумма денежных средств в наличии'),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='date_saldo_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='deposit_start_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Сумма денег на депозитных счетах'),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='investment_start_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Сумма денег в инвестиционных активах'),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='long_debt_start_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Сумма долгов с возвратом в течение более 12 мес'),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='short_debt_start_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Сумма долгов с возвратом в течение 12 мес'),
        ),
    ]
