# Generated by Django 5.1.7 on 2025-04-15 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='Без названия', max_length=100, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание транзакции'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='transactions.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category'),
        ),
    ]
