# Generated by Django 5.1.7 on 2025-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Доходы', 'Доходы'), ('Расходы', 'Расходы'), ('Депозит', 'Депозит'), ('Долг', 'Долг')], max_length=100, verbose_name='Целевое использование')),
                ('sub_category', models.CharField(max_length=100, verbose_name='Подкатегория')),
                ('description', models.TextField(blank=True, verbose_name='Заметка')),
            ],
        ),
    ]
