# Generated by Django 5.1.7 on 2025-04-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_subcategory_delete_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('income', 'Доходы'), ('expense', 'Расходы'), ('deposit', 'Депозит'), ('investment', 'Инвестиции'), ('debt', 'Долг')], max_length=100, verbose_name='Вид операции'),
        ),
    ]
